import { useState, useEffect } from "react";

const mockTodayData = [
  {
    entries: [
      {
        id: "dd3X7JCm9ZeNy6HFPCyC",
        data: {
          highTide: "",
          tagSuccess: "not-noted",
          area: "Bimini",
          audioRec: "",
          encounterNumber: "",
          startTimestamp: new Date("2020-08-13T23:00:00.000Z"),
          lowTide: "",
          numSubAdultMale: "",
          biopsySuccess: "not-noted",
          exported: true,
          project: "",
          visualIdentifications: "",
          numYoungOfYear: "",
          logbookNumber: "",
          numSubAdult: "",
          comments: "",
          species: "Bottlenose dolphin - oceanic",
          location: "",
          needsToBeChecked: true,
          numAdultFemale: "",
          elapsedTime: "",
          numSubAdultFemale: "",
          groupSize: "",
          transect: "Off",
          numJuvenileFemale: "",
          endTime: "",
          videoRec: "",
          numAdultMale: "",
          tagAttempt: "No",
          numNeonates: "",
          vessel: "",
          numUnknown: "",
          sequenceNumber: "E777",
          enteredBy: "Research Assistant",
          cue: "",
          reasonForLeaving: "",
          exportedOn: {
            seconds: 1597312483,
            nanoseconds: 917000000,
          },
          numJuvenileMale: "",
          observers: "",
          endOfSearchEffort: "",
          biopsyAttempt: "No",
          numAdultUnknown: "",
          startTime: "10:14",
          photographerFrameNumber: "",
          numJuvenileUnknown: "",
        },
      },
      {
        id: "wTUC5WV4Vcvt6rW89rnt",
        data: {
          encounterNumber: "",
          exportedOn: {
            seconds: 1597312483,
            nanoseconds: 917000000,
          },
          endOfSearchEffort: "",
          species: "Bottlenose dolphin - oceanic",
          vessel: "",
          numAdultFemale: "",
          photographerFrameNumber: "",
          numSubAdultMale: "",
          area: "Cat Island",
          highTide: "",
          needsToBeChecked: true,
          transect: "Off",
          numYoungOfYear: "",
          elapsedTime: "",
          comments: "",
          biopsyAttempt: "No",
          numSubAdultFemale: "",
          tagSuccess: "not-noted",
          videoRec: "",
          visualIdentifications: "",
          cue: "",
          startTime: "10:42",
          numAdultUnknown: "",
          numNeonates: "",
          location: "",
          reasonForLeaving: "",
          audioRec: "",
          project: "",
          endTime: "",
          lowTide: "",
          numJuvenileUnknown: "",
          numSubAdult: "",
          sequenceNumber: "E99",
          exported: true,
          logbookNumber: "",
          tagAttempt: "No",
          startTimestamp: new Date("2020-08-13T23:00:00.000Z"),
          numJuvenileFemale: "",
          observers: "",
          numUnknown: "",
          numJuvenileMale: "",
          enteredBy: "Research Assistant",
          numAdultMale: "",
          biopsySuccess: "not-noted",
          groupSize: "",
        },
      },
    ],
  },
];

const mockPreviousData = [
  {
    month: "July",
    year: 2020,
    entries: [
      {
        id: "55a5GnQinPGq9H8x0gRO",
        data: {
          numUnknown: "",
          elapsedTime: "",
          needsToBeChecked: true,
          species: "Blainville's beaked whale",
          biopsyAttempt: "No",
          endOfSearchEffort: "",
          biopsySuccess: "not-noted",
          tagAttempt: "No",
          encounterNumber: "",
          numSubAdultMale: "",
          project: "BMMRO_land",
          location: "",
          numAdultMale: "",
          sequenceNumber: "5f",
          transect: "Off",
          exported: true,
          highTide: "",
          startTimestamp: new Date("2020-07-02T23:00:00.000Z"),
          visualIdentifications: "",
          numSubAdult: "",
          vessel: "",
          lowTide: "",
          numSubAdultFemale: "",
          reasonForLeaving: "",
          logbookNumber: "",
          numJuvenileMale: "",
          numAdultUnknown: "",
          endTime: "",
          groupSize: "",
          enteredBy: "Research Assistant",
          observers: "",
          photographerFrameNumber: "",
          area: "EA",
          audioRec: "",
          cue: "",
          comments: "",
          numYoungOfYear: "",
          exportedOn: {
            seconds: 1597252231,
            nanoseconds: 190000000,
          },
          videoRec: "",
          startTime: "16:51",
          tagSuccess: "not-noted",
          numJuvenileUnknown: "",
          numNeonates: "",
          numJuvenileFemale: "",
          numAdultFemale: "",
        },
      },
      {
        id: "LXcY1neE1cHsUCATwGJE",
        data: {
          numAdultFemale: "",
          numUnknown: "",
          startTime: "15:25",
          observers: "",
          endTime: "",
          highTide: "",
          numSubAdultFemale: "",
          numYoungOfYear: "",
          sequenceNumber: "23dfsd23423fds",
          numNeonates: "",
          reasonForLeaving: "",
          location: "",
          numSubAdultMale: "",
          exportedOn: {
            seconds: 1597252231,
            nanoseconds: 190000000,
          },
          visualIdentifications: "",
          tagSuccess: "not-noted",
          exported: true,
          videoRec: "",
          cue: "",
          numAdultMale: "",
          needsToBeChecked: true,
          lowTide: "",
          comments: "",
          project: "",
          vessel: "",
          audioRec: "",
          numJuvenileUnknown: "",
          startTimestamp: new Date("2020-07-11T23:00:00.000Z"),
          numJuvenileFemale: "",
          enteredBy: "Research Assistant",
          biopsyAttempt: "No",
          species: "Bottlenose dolphin - coastal",
          numAdultUnknown: "",
          numJuvenileMale: "",
          elapsedTime: "",
          encounterNumber: "",
          biopsySuccess: "not-noted",
          groupSize: "",
          area: "Cay Sal",
          endOfSearchEffort: "",
          transect: "Off",
          logbookNumber: "",
          tagAttempt: "No",
          photographerFrameNumber: "",
          numSubAdult: "",
        },
      },
    ],
  },
  {
    month: "June",
    year: 2020,
    entries: [
      {
        id: "Phqc0OgG1Qac9qqo72ka",
        data: {
          enteredBy: "Research Assistant",
          exported: true,
          logbookNumber: "",
          photographerFrameNumber: "",
          biopsyAttempt: "No",
          elapsedTime: "",
          numSubAdult: "",
          reasonForLeaving: "",
          numUnknown: "",
          tagAttempt: "No",
          project: "",
          numNeonates: "",
          exportedOn: {
            seconds: 1597312747,
            nanoseconds: 762000000,
          },
          sequenceNumber: "E777",
          groupSize: "",
          transect: "Off",
          lowTide: "",
          visualIdentifications: "",
          vessel: "",
          numJuvenileUnknown: "",
          audioRec: "",
          startTime: "10:50",
          location: "",
          species: "Clymene dolphin",
          numJuvenileMale: "",
          area: "Bimini",
          comments: "",
          numSubAdultMale: "",
          numJuvenileFemale: "",
          numAdultFemale: "",
          numAdultMale: "",
          biopsySuccess: "not-noted",
          numYoungOfYear: "",
          startTimestamp: new Date("2020-06-12T23:00:00.000Z"),
          tagSuccess: "not-noted",
          encounterNumber: "",
          needsToBeChecked: true,
          videoRec: "",
          cue: "",
          numSubAdultFemale: "",
          observers: "",
          numAdultUnknown: "",
          highTide: "",
          endOfSearchEffort: "",
          endTime: "",
        },
      },
      {
        id: "Rb9rp9CtcuzyCgVccE4J",
        data: {
          cue: "",
          audioRec: "",
          sequenceNumber: "1234",
          logbookNumber: "",
          enteredBy: "Research Assistant",
          encounterNumber: "",
          tagAttempt: "No",
          tagSuccess: "not-noted",
          vessel: "",
          reasonForLeaving: "",
          endTime: "",
          lowTide: "",
          comments: "",
          numAdultFemale: "",
          numYoungOfYear: "",
          biopsySuccess: "not-noted",
          numSubAdultFemale: "",
          numJuvenileFemale: "",
          needsToBeChecked: true,
          exported: true,
          endOfSearchEffort: "",
          numJuvenileUnknown: "",
          observers: "",
          startTime: "16:18",
          numUnknown: "",
          location: "",
          numSubAdult: "",
          elapsedTime: "",
          highTide: "",
          area: "Long Island",
          numAdultMale: "",
          videoRec: "",
          visualIdentifications: "",
          groupSize: "",
          numJuvenileMale: "",
          startTimestamp: new Date("2020-06-11T22:00:00.000Z"),
          transect: "Off",
          exportedOn: {
            seconds: 1597252231,
            nanoseconds: 190000000,
          },
          photographerFrameNumber: "",
          biopsyAttempt: "No",
          numNeonates: "",
          numAdultUnknown: "",
          numSubAdultMale: "",
          species: "Unknown mesoplodon species",
          project: "",
        },
      },
      {
        id: "SsNiqxzcpU08dyd3r7dV",
        data: {
          tagAttempt: "No",
          sequenceNumber: "E01",
          species: "Atlantic spotted dolphin",
          numJuvenileUnknown: "",
          cue: "",
          reasonForLeaving: "",
          project: "",
          tagSuccess: "not-noted",
          numSubAdultMale: "",
          numNeonates: "",
          observers: "",
          numSubAdult: "",
          comments: "",
          numAdultFemale: "",
          startTime: "10:54",
          numSubAdultFemale: "",
          logbookNumber: "",
          audioRec: "",
          location: "",
          needsToBeChecked: true,
          biopsySuccess: "not-noted",
          numYoungOfYear: "",
          numJuvenileMale: "",
          highTide: "",
          endTime: "",
          numUnknown: "",
          numAdultUnknown: "",
          numJuvenileFemale: "",
          exported: true,
          exportedOn: {
            seconds: 1597312747,
            nanoseconds: 762000000,
          },
          area: "Central Andros",
          videoRec: "",
          groupSize: "",
          startTimestamp: new Date("2020-06-16T23:00:00.000Z"),
          endOfSearchEffort: "",
          transect: "Off",
          enteredBy: "Research Assistant",
          vessel: "",
          biopsyAttempt: "No",
          photographerFrameNumber: "",
          numAdultMale: "",
          visualIdentifications: "",
          encounterNumber: "",
          elapsedTime: "",
          lowTide: "",
        },
      },
      {
        id: "ZRvJA5z3QQS3QaYaQlX2",
        data: {
          numYoungOfYear: 33,
          highTide: "14:13",
          transect: "Off",
          species: "Curvier's beaked whale",
          exported: true,
          transectNumber: "dfgdfg34",
          tagAttempt: "No",
          endOfSearchEffort: "12:12",
          numSubAdultFemale: 0,
          comments: "Testing on thursday",
          groupSize: 12,
          numAdultMale: 3453,
          elapsedTime: 1,
          reasonForLeaving: "Low Priority species",
          area: "Cul de Sac",
          numAdultFemale: 45,
          enteredBy: "Research Assistant",
          project: "CCRC",
          location: "Near sea wall",
          lowTide: "15:12",
          numSubAdultMale: 0,
          encounterNumber: 2345,
          biopsySuccess: "not-noted",
          numJuvenileUnknown: 4567,
          observers: "Jen, Linda and Flavia",
          videoRec: "6534tfgdfgbdgn",
          startTime: "10:48",
          numNeonates: 5656,
          sequenceNumber: "3785479dlkfghjlfbfd",
          numJuvenileMale: 456,
          vessel: "Not Noted",
          numUnknown: 9,
          needsToBeChecked: true,
          logbookNumber: "e5456",
          photographerFrameNumber: 3475,
          startTimestamp: new Date("2020-06-04T23:00:00.000Z"),
          audioRec: "erflkjl53453fgbhetr",
          biopsyAttempt: "No",
          endTime: "10:49",
          cue: "M3R",
          numAdultUnknown: 3453,
          numJuvenileFemale: 5,
          tagSuccess: "not-noted",
          numSubAdult: 0,
          visualIdentifications: "",
          exportedOn: {
            seconds: 1597312747,
            nanoseconds: 762000000,
          },
        },
      },
    ],
  },
  { month: "May", year: 2020, entries: [] },
  {
    month: "April",
    year: 2020,
    entries: [
      {
        id: "dd3X7JCm9ZeNy6HFPCyC",
        data: {
          highTide: "",
          tagSuccess: "not-noted",
          area: "Bimini",
          audioRec: "",
          encounterNumber: "",
          startTimestamp: new Date("2020-04-21T23:00:00.000Z"),
          lowTide: "",
          numSubAdultMale: "",
          biopsySuccess: "not-noted",
          exported: true,
          project: "",
          visualIdentifications: "",
          numYoungOfYear: "",
          logbookNumber: "",
          numSubAdult: "",
          comments: "",
          species: "Bottlenose dolphin - oceanic",
          location: "",
          needsToBeChecked: true,
          numAdultFemale: "",
          elapsedTime: "",
          numSubAdultFemale: "",
          groupSize: "",
          transect: "Off",
          numJuvenileFemale: "",
          endTime: "",
          videoRec: "",
          numAdultMale: "",
          tagAttempt: "No",
          numNeonates: "",
          vessel: "",
          numUnknown: "",
          sequenceNumber: "E777",
          enteredBy: "Research Assistant",
          cue: "",
          reasonForLeaving: "",
          exportedOn: {
            seconds: 1597312483,
            nanoseconds: 917000000,
          },
          numJuvenileMale: "",
          observers: "",
          endOfSearchEffort: "",
          biopsyAttempt: "No",
          numAdultUnknown: "",
          startTime: "10:14",
          photographerFrameNumber: "",
          numJuvenileUnknown: "",
        },
      },
      {
        id: "wTUC5WV4Vcvt6rW89rnt",
        data: {
          encounterNumber: "",
          exportedOn: {
            seconds: 1597312483,
            nanoseconds: 917000000,
          },
          endOfSearchEffort: "",
          species: "Bottlenose dolphin - oceanic",
          vessel: "",
          numAdultFemale: "",
          photographerFrameNumber: "",
          numSubAdultMale: "",
          area: "Cat Island",
          highTide: "",
          needsToBeChecked: true,
          transect: "Off",
          numYoungOfYear: "",
          elapsedTime: "",
          comments: "",
          biopsyAttempt: "No",
          numSubAdultFemale: "",
          tagSuccess: "not-noted",
          videoRec: "",
          visualIdentifications: "",
          cue: "",
          startTime: "10:42",
          numAdultUnknown: "",
          numNeonates: "",
          location: "",
          reasonForLeaving: "",
          audioRec: "",
          project: "",
          endTime: "",
          lowTide: "",
          numJuvenileUnknown: "",
          numSubAdult: "",
          sequenceNumber: "E99",
          exported: true,
          logbookNumber: "",
          tagAttempt: "No",
          startTimestamp: new Date("2020-04-12T23:00:00.000Z"),
          numJuvenileFemale: "",
          observers: "",
          numUnknown: "",
          numJuvenileMale: "",
          enteredBy: "Research Assistant",
          numAdultMale: "",
          biopsySuccess: "not-noted",
          groupSize: "",
        },
      },
    ],
  },
];

const useEncountersByMonth = (datastore) => {
  const [todaysEncounters, setTodaysEncounters] = useState([]);
  const [previousEncounters, setPreviousEncounters] = useState([]);

  useEffect(() => {
    setTodaysEncounters(mockTodayData);
    setPreviousEncounters(mockPreviousData);
  }, []);

  return [
    todaysEncounters,
    previousEncounters,
    () => alert("Set next month's data! 😱"),
  ];
};

export default useEncountersByMonth;
