export const mockSingleDayData = [
  {
    entries: [
      {
        id: "dd3X7JCm9ZeNy6HFPCyC",
        data: {
          highTide: "",
          tagSuccess: "not-noted",
          area: "Bimini",
          audioRec: "",
          encounterNumber: "",
          startTimestamp: new Date("2020-08-13T23:00:00.000Z"),
          lowTide: "",
          numSubAdultMale: "",
          biopsySuccess: "not-noted",
          exported: true,
          project: "",
          visualIdentifications: "",
          numYoungOfYear: "",
          logbookNumber: "",
          numSubAdult: "",
          comments: "",
          species: "Bottlenose dolphin - oceanic",
          location: "",
          needsToBeChecked: true,
          numAdultFemale: "",
          elapsedTime: "",
          numSubAdultFemale: "",
          lowEstimate: "",
          bestEstimate: "",
          highEstimate: "",
          transect: "Off",
          numJuvenileFemale: "",
          endTime: "",
          videoRec: "",
          numAdultMale: "",
          tagAttempt: "No",
          numNeonates: "",
          vessel: "",
          numUnknown: "",
          sequenceNumber: "E777",
          enteredBy: "Research Assistant",
          cue: "",
          reasonForLeaving: "",
          exportedOn: {
            seconds: 1597312483,
            nanoseconds: 917000000,
          },
          numJuvenileMale: "",
          observers: "",
          endOfSearchEffort: "",
          biopsyAttempt: "No",
          numAdultUnknown: "",
          startTime: "10:14",
          photographerFrame: "",
          numJuvenileUnknown: "",
        },
      },
      {
        id: "wTUC5WV4Vcvt6rW89rnt",
        data: {
          encounterNumber: "",
          exportedOn: {
            seconds: 1597312483,
            nanoseconds: 917000000,
          },
          endOfSearchEffort: "",
          species: "Bottlenose dolphin - oceanic",
          vessel: "",
          numAdultFemale: "",
          photographerFrame: "",
          numSubAdultMale: "",
          area: "Cat Island",
          highTide: "",
          needsToBeChecked: true,
          transect: "Off",
          numYoungOfYear: "",
          elapsedTime: "",
          comments: "",
          biopsyAttempt: "No",
          numSubAdultFemale: "",
          tagSuccess: "not-noted",
          videoRec: "",
          visualIdentifications: "",
          cue: "",
          startTime: "10:42",
          numAdultUnknown: "",
          numNeonates: "",
          location: "",
          reasonForLeaving: "",
          audioRec: "",
          project: "",
          endTime: "",
          lowTide: "",
          numJuvenileUnknown: "",
          numSubAdult: "",
          sequenceNumber: "E99",
          exported: true,
          logbookNumber: "",
          tagAttempt: "No",
          startTimestamp: new Date("2020-08-13T23:00:00.000Z"),
          numJuvenileFemale: "",
          observers: "",
          numUnknown: "",
          numJuvenileMale: "",
          enteredBy: "Research Assistant",
          numAdultMale: "",
          biopsySuccess: "not-noted",
          lowEstimate: "",
          bestEstimate: "",
          highEstimate: "",
        },
      },
    ],
  },
];

export const mockSingleMonthData = [
  {
    month: "August",
    year: 2020,
    entries: [
      {
        id: "55a5GnQinPGq9H8x0gRO",
        data: {
          numUnknown: "",
          elapsedTime: "",
          needsToBeChecked: true,
          species: "Blainville's beaked whale",
          biopsyAttempt: "No",
          endOfSearchEffort: "",
          biopsySuccess: "not-noted",
          tagAttempt: "No",
          encounterNumber: "",
          numSubAdultMale: "",
          project: "BMMRO_land",
          location: "",
          numAdultMale: "",
          sequenceNumber: "5f",
          transect: "Off",
          exported: true,
          highTide: "",
          startTimestamp: new Date("2020-07-02T23:00:00.000Z"),
          visualIdentifications: "",
          numSubAdult: "",
          vessel: "",
          lowTide: "",
          numSubAdultFemale: "",
          reasonForLeaving: "",
          logbookNumber: "",
          numJuvenileMale: "",
          numAdultUnknown: "",
          endTime: "",
          lowEstimate: "",
          bestEstimate: "",
          highEstimate: "",
          enteredBy: "Research Assistant",
          observers: "",
          photographerFrame: "",
          area: "EA",
          audioRec: "",
          cue: "",
          comments: "",
          numYoungOfYear: "",
          exportedOn: {
            seconds: 1597252231,
            nanoseconds: 190000000,
          },
          videoRec: "",
          startTime: "16:51",
          tagSuccess: "not-noted",
          numJuvenileUnknown: "",
          numNeonates: "",
          numJuvenileFemale: "",
          numAdultFemale: "",
        },
      },
      {
        id: "LXcY1neE1cHsUCATwGJE",
        data: {
          numAdultFemale: "",
          numUnknown: "",
          startTime: "15:25",
          observers: "",
          endTime: "",
          highTide: "",
          numSubAdultFemale: "",
          numYoungOfYear: "",
          sequenceNumber: "23dfsd23423fds",
          numNeonates: "",
          reasonForLeaving: "",
          location: "",
          numSubAdultMale: "",
          exportedOn: {
            seconds: 1597252231,
            nanoseconds: 190000000,
          },
          visualIdentifications: "",
          tagSuccess: "not-noted",
          exported: true,
          videoRec: "",
          cue: "",
          numAdultMale: "",
          needsToBeChecked: true,
          lowTide: "",
          comments: "",
          project: "",
          vessel: "",
          audioRec: "",
          numJuvenileUnknown: "",
          startTimestamp: new Date("2020-07-11T23:00:00.000Z"),
          numJuvenileFemale: "",
          enteredBy: "Research Assistant",
          biopsyAttempt: "No",
          species: "Bottlenose dolphin - coastal",
          numAdultUnknown: "",
          numJuvenileMale: "",
          elapsedTime: "",
          encounterNumber: "",
          biopsySuccess: "not-noted",
          lowEstimate: "",
          bestEstimate: "",
          highEstimate: "",
          area: "Cay Sal",
          endOfSearchEffort: "",
          transect: "Off",
          logbookNumber: "",
          tagAttempt: "No",
          photographerFrame: "",
          numSubAdult: "",
        },
      },
    ],
  },
];

export const mockMultiMonthData = [
  {
    month: "August",
    year: 2020,
    entries: [
      {
        id: "55a5GnQinPGq9H8x0gRO",
        data: {
          numUnknown: "",
          elapsedTime: "",
          needsToBeChecked: true,
          species: "Blainville's beaked whale",
          biopsyAttempt: "No",
          endOfSearchEffort: "",
          biopsySuccess: "not-noted",
          tagAttempt: "No",
          encounterNumber: "",
          numSubAdultMale: "",
          project: "BMMRO_land",
          location: "",
          numAdultMale: "",
          sequenceNumber: "5f",
          transect: "Off",
          exported: true,
          highTide: "",
          startTimestamp: new Date("2020-07-02T23:00:00.000Z"),
          visualIdentifications: "",
          numSubAdult: "",
          vessel: "",
          lowTide: "",
          numSubAdultFemale: "",
          reasonForLeaving: "",
          logbookNumber: "",
          numJuvenileMale: "",
          numAdultUnknown: "",
          endTime: "",
          lowEstimate: "",
          bestEstimate: "",
          highEstimate: "",
          enteredBy: "Research Assistant",
          observers: "",
          photographerFrame: "",
          area: "EA",
          audioRec: "",
          cue: "",
          comments: "",
          numYoungOfYear: "",
          exportedOn: {
            seconds: 1597252231,
            nanoseconds: 190000000,
          },
          videoRec: "",
          startTime: "16:51",
          tagSuccess: "not-noted",
          numJuvenileUnknown: "",
          numNeonates: "",
          numJuvenileFemale: "",
          numAdultFemale: "",
        },
      },
      {
        id: "LXcY1neE1cHsUCATwGJE",
        data: {
          numAdultFemale: "",
          numUnknown: "",
          startTime: "15:25",
          observers: "",
          endTime: "",
          highTide: "",
          numSubAdultFemale: "",
          numYoungOfYear: "",
          sequenceNumber: "23dfsd23423fds",
          numNeonates: "",
          reasonForLeaving: "",
          location: "",
          numSubAdultMale: "",
          exportedOn: {
            seconds: 1597252231,
            nanoseconds: 190000000,
          },
          visualIdentifications: "",
          tagSuccess: "not-noted",
          exported: true,
          videoRec: "",
          cue: "",
          numAdultMale: "",
          needsToBeChecked: true,
          lowTide: "",
          comments: "",
          project: "",
          vessel: "",
          audioRec: "",
          numJuvenileUnknown: "",
          startTimestamp: new Date("2020-07-11T23:00:00.000Z"),
          numJuvenileFemale: "",
          enteredBy: "Research Assistant",
          biopsyAttempt: "No",
          species: "Bottlenose dolphin - coastal",
          numAdultUnknown: "",
          numJuvenileMale: "",
          elapsedTime: "",
          encounterNumber: "",
          biopsySuccess: "not-noted",
          lowEstimate: "",
          bestEstimate: "",
          highEstimate: "",
          area: "Cay Sal",
          endOfSearchEffort: "",
          transect: "Off",
          logbookNumber: "",
          tagAttempt: "No",
          photographerFrame: "",
          numSubAdult: "",
        },
      },
    ],
  },
  {
    month: "June",
    year: 2020,
    entries: [
      {
        id: "Phqc0OgG1Qac9qqo72ka",
        data: {
          enteredBy: "Research Assistant",
          exported: true,
          logbookNumber: "",
          photographerFrame: "",
          biopsyAttempt: "No",
          elapsedTime: "",
          numSubAdult: "",
          reasonForLeaving: "",
          numUnknown: "",
          tagAttempt: "No",
          project: "",
          numNeonates: "",
          exportedOn: {
            seconds: 1597312747,
            nanoseconds: 762000000,
          },
          sequenceNumber: "E777",
          lowEstimate: "",
          bestEstimate: "",
          highEstimate: "",
          transect: "Off",
          lowTide: "",
          visualIdentifications: "",
          vessel: "",
          numJuvenileUnknown: "",
          audioRec: "",
          startTime: "10:50",
          location: "",
          species: "Clymene dolphin",
          numJuvenileMale: "",
          area: "Bimini",
          comments: "",
          numSubAdultMale: "",
          numJuvenileFemale: "",
          numAdultFemale: "",
          numAdultMale: "",
          biopsySuccess: "not-noted",
          numYoungOfYear: "",
          startTimestamp: new Date("2020-06-12T23:00:00.000Z"),
          tagSuccess: "not-noted",
          encounterNumber: "",
          needsToBeChecked: true,
          videoRec: "",
          cue: "",
          numSubAdultFemale: "",
          observers: "",
          numAdultUnknown: "",
          highTide: "",
          endOfSearchEffort: "",
          endTime: "",
        },
      },
    ],
  },
];
