const biopsyFormDefaultValues = {
  areaHit: "",
  dorsalHit: "",
  whaleSide: "",
  species: "",
  samplerName: "",
  sampleNumber: "",
  attempt: "",
  dateTaken: "",
  timeTaken: "",
  latitude: "",
  longitude: "",
  gpsMark: "",
  totalSpecimens: "",
  dartHit: "",
  dartStuck: "",
  dartRetrieved: "",
  sampleType: "",
  photographerInitials: "",
  video: "",
  whaleID: "",
  sex: "",
  age: "",
  projectorType: "",
  model: "",
  tipLength: "",
  range: "",
  angle: "",
  groupBehaviourBeforeBiopsy: "",
  groupBehaviourAfterBiopsy: "",
  otherObservations: "",
  exported: false,
  hasEnded: false,
  reactionStrength: "",
  extent: "",
  targetAnimalBehaviour: {
    accelerated: false,
    shake: false,
    startle: false,
    tailSplash: false,
    tailSlap: false,
    lunge: false,
    breach: false,
    dive: false,
    porpoising: false,
    flight: false,
    prolongedFlight: false,
    directionChange: false,
  },
  nonTargetAnimalBehaviour: {
    accelerated: false,
    shake: false,
    startle: false,
    tailSplash: false,
    tailSlap: false,
    lunge: false,
    breach: false,
    dive: false,
    porpoising: false,
    flight: false,
    prolongedFlight: false,
    directionChange: false,
  },
  specimens: [
    {
      specimenNumber: "",
      sampleType: "",
      storageType: "",
    },
  ],
};

export default biopsyFormDefaultValues;
