export default {
  areaHit: "",
  dorsalHit: "",
  whaleSide: "",
  species: "",
  samplerName: "",
  attempt: "",
  dateTaken: "",
  timeTaken: "",
  latitude: "",
  longitude: "",
  gpsMark: "",
  totalSpecimens: "",
  dartHit: "",
  dartStuck: "",
  dartRetrieved: "",
  sampleType: "",
  exported: false,
  hasEnded: false,
  reactionStrength: "",
  "targetAnimal.Shake": false,
  "targetAnimal.Startle": false,
  "targetAnimal.Tail Splash": false,
  "targetAnimal.Tail Slap": false,
  "targetAnimal.Lunge": false,
  "targetAnimal.Breach": false,
  "targetAnimal.Dive": false,
  "targetAnimal.Porpoising": false,
  "targetAnimal.Flight": false,
  "targetAnimal.Prolonged Flight": false,
  "targetAnimal.Direction Change": false,
};
