export default {
  areaHit: "",
  dorsalHit: "",
  whaleSide: "",
  species: "",
  samplerName: "",
  sampleNumber: "",
  attempt: "",
  dateTaken: "",
  timeTaken: "",
  latitude: "",
  longitude: "",
  gpsMark: "",
  totalSpecimens: "",
  dartHit: "",
  dartStuck: "",
  dartRetrieved: "",
  sampleType: "",
  whaleID: "",
  sex: "",
  age: "",
  exported: false,
  hasEnded: false,
  specimens: [
    {
      specimenNumber: "",
      sampleType: "",
      storageType: "",
    },
  ],
};
