import { RESEARCH_ASSISTANT } from "./formOptions/roles";

const encounterDefaultValues = {
  sequenceNumber: "",
  startTimestamp: "",
  area: "",
  species: "",
  project: "",
  cue: "",
  vessel: "",
  observers: "",
  numberOfAnimalsLow: "",
  numberOfAnimalsBest: "",
  numberOfAnimalsHigh: "",
  location: "",
  comments: "",
  videoRec: "",
  audioRec: "",
  photographerFrame: "",
  visualIdentifications: "",
  biopsyAttempt: "No",
  biopsySuccess: "not-noted",
  tagAttempt: "No",
  tagSuccess: "not-noted",
  transect: "Off",
  numAdultMale: "",
  numAdultFemale: "",
  numAdultUnknown: "",
  numSubAdultMale: "",
  numSubAdultFemale: "",
  numSubAdult: "",
  numJuvenileMale: "",
  numJuvenileFemale: "",
  numJuvenileUnknown: "",
  numYoungOfYear: "",
  numNeonates: "",
  numUnknown: "",
  endOfSearchEffort: "",
  endTimestamp: "",
  endTime: "",
  reasonForLeaving: "",
  highTide: "",
  lowTide: "",
  logbookNumber: "",
  encounterNumber: "",
  startTime: "",
  elapsedTime: "",
  enteredBy: RESEARCH_ASSISTANT,
  needsToBeChecked: true,
  exported: false,
  hasEnded: false,
};

export default encounterDefaultValues;
