export default {
  time: "",
  latitude: "",
  longitude: "",
  gpsMark: "",
  waterDepth: "",
  waterDepthBeyondSoundings: false,
  waterTemp: "",
  bottomSubstrate: "",
  cloudCover: "",
  beaufortSeaState: "",
  waveHeight: "",
  hydrophoneChecked: "No",
  efforted: "On",
  hydrophoneComments: "",
  logbookComments: "",
};
