export default {
  tripId: "",
  tripNumber: "",
  date: "",
  time: "",
  area: "",
  vessel: "",
  gpsFileName: "",
  project: "",
  observers: "",
  numberOfObservers: "",
  engineHoursMeterReading: "",
  windSpeed: "",
  windDirection: "",
  comments: "",
};
