module.exports = {
  habitatUse: {
    Area: "",
    Date: "date",
    "Sequence #": "encSeqNo",
    Time: "startTime",
    Latitude: "latitude",
    Longitude: "longitude",
    "Water temperature": "waterTemp",
    "Water depth": "waterDepth",
    "Bottom substrate": "bottomSubstrate",
    "Cloud cover": "cloudCover",
    "Beaufort scale": "beaufortSeaState",
    "Tide state": "tideState",
    Behaviour: "behaviour",
    "Number of boats": "numberOfBoats",
    "Wave Height": "swellWaveHeight",
    DOT: "",
    "Surfacing Bout": "surfaceBout",
    "Tagged Whale?": "",
    "Bearing (relative )": "bearing",
    Distance: "distance",
    "Aspect (relative)": "aspect",
    "Non-Tagged Surfacing Counts": "",
    "Tagged Surfacing Counts": "",
    "Group Cohesion": "groupCohesion",
    "End Time": "endTime",
    "Group Composition": "groupComposition",
    "# animals": "numberOfAnimals",
    Comment: "comments",
  },
};
