export const CollectionNames = {
  HABITAT_USE: "habitatUse",
};

export const DatastoreErrorType = {
  UNKNOWN_OFFLINE_SUPPORT: "UNKNOWN_OFFLINE_SUPPORT",
  MULTIPLE_TABS: "MULTIPLE_TABS",
  BROWSER_NOT_SUPPORTED: "BROWSER_NOT_SUPPORTED",
  COLLECTION_ENTRY: "COLLECTION_ENTRY",
  INITIALIZATION: "INITIALIZATION",
};
