export default [
  "SA",
  "EA",
  "Central Andros",
  "Bimini",
  "Cat Island",
  "Cay Sal",
  "Central Abaco",
  "Conception Island",
  "Crooked/Aklins",
  "Cul de Sac",
  "East Berry Islands",
  "East Grand Bahama",
  "Inagua",
  "Long Island",
  "Mayaguana",
  "Mira por Vos Cays",
  "NA",
  "NB",
  "New Providence",
  "North Andros",
  "North Berry Islands",
  "North Eleuthera",
  "North Exuma Cays",
  "North Grand Bahama",
  "Not Noted",
  "Plana Cays",
  "Ragged Island",
  "Rum Cay",
  "San Salvador",
  "South Andros",
  "South Berry Islands",
  "South Eleuthera",
  "South Exuma Cays",
  "South Grand Bahama",
  "UK",
  "WA",
  "West Andros",
  "West Grand Bahama",
];
