export default [
  "TEST BEHAVIOUR",
  "Arch",
  "Behaviour state",
  "Breach",
  "Chase",
  "Chin slap",
  "Feed",
  "Feed/social",
  "Feed/travel",
  "Flipper out",
  "Flipper slap",
  "Fluke out",
  "Head slap",
  "Join",
  "Leap",
  "Leave",
  "Logging",
  "Milling",
  "Milling/social",
  "Not Noted",
  "Play",
  "Porpoising",
  "Rest",
  "Rest/feed",
  "Rest/milling",
  "Rest/social",
  "Social",
  "Social/travel",
  "Spyhop",
  "Surface",
  "Tail slap",
  "Travel - fast",
  "Travel - moderate",
  "Travel - slow",
  "Travel",
];
