export default [
  "ABPF - Dolphin Decline",
  "ABPF - Stranding",
  "ABPF - research",
  "AUTEC Health",
  "BBES",
  "BMMRO",
  "BMMRO_land",
  "BPAF - Dolphin Decline",
  "BRS",
  "CCRC",
  "CDM",
  "CEI",
  "Dev - Dolphin Decline",
  "Dev - Shared Waters",
  "DWCF",
  "Dtag",
  "Hex",
  "Kogia - Aarhus",
  "M3R",
  "Manatees",
  "Michael Gould",
  "NEA Fecal",
  "NEAq",
  "Not Noted",
  "ONR eDNA",
  "ONR Stress",
  "Post Dorian",
  "Prey Mapping",
  "Public",
  "SCC",
  "SCC/Stress",
  "SERDP",
  "Sea of Abaco",
  "Shared Waters",
  "Silverback",
  "Vital Rates",
  "Whale Camp",
  "Wild Dolphin Project",
];
