const species = [
  "Bottlenose dolphin - coastal",
  "Blainville's beaked whale",
  "Dwarf sperm whale",
  "Sperm whale",
  "Atlantic spotted dolphin",
  "Bottlenose dolphin - oceanic",
  "Clymene dolphin",
  "Cuvier's beaked whale",
  "False killer whale",
  "Fin whale",
  "Fraser's dolphin",
  "Gervais' beaked whale",
  "Hooded seal",
  "Humpback whale",
  "Killer whale",
  "Melon-headed whale",
  "Minke whale",
  "Northern bottlenose whale",
  "Not Noted",
  "Pan-tropical spotted dolphin",
  "Pygmy killer whale",
  "Pygmy sperm whale",
  "Risso's dolphin",
  "Rough-toothed dolphin",
  "Short-finned pilot whale",
  "Stenella sp.",
  "Striped dolphin",
  "Unknown balaenopterid",
  "Unknown cetacean",
  "Unknown small cetacean",
  "Unknown medium cetacean",
  "Unknown large cetacean",
  "Unknown delphinid",
  "Unknown kogia species",
  "Unknown mesoplodon species",
  "Unknown pinniped",
  "Unknown ziphiid species",
  "West Indian manatee",
];
export default species;
