export const fields = [
  {
    name: "date",
    label: "Date",
    placeholder: "mm/dd/yyyy",
    type: "date",
    required: true,
  },
  {
    name: "encSeqNo",
    label: "Enc Seq #",
    placeholder: "1",
    type: "number",
    required: true,
  },
  {
    name: "species",
    label: "Species",
    placeholder: "whale",
    type: "text",
    required: true,
  },
  {
    name: "time",
    label: "Time",
    placeholder: "12:00",
    type: "time",
    required: true,
  },
  {
    name: "latitude",
    label: "Lat",
    placeholder: "lat",
    type: "text",
    required: true,
  },
  {
    name: "longitude",
    label: "Long",
    placeholder: "long",
    type: "text",
    required: true,
  },
  {
    name: "waterDepth",
    label: "Water Depth",
    placeholder: "1",
    type: "number",
    required: true,
  },
  {
    name: "waterTemp",
    label: "Water Temp",
    placeholder: "1",
    type: "number",
    required: true,
  },
];
