name: Backup database

on:
  schedule:
    - cron:  '00 14 * * *'

env:
  PROJECT_ID: ${{secrets.FIREBASE_DEV_PROJECT_ID}}
  BUCKET: gs://${{secrets.BUCKET_DEV}}

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        name: 'Authenticate to google cloud'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.BACKUP_KEY }}
      - uses: google-github-actions/setup-gcloud@v1
        run: |-
          gcloud info
          gcloud config set project $PROJECT_ID
          gcloud firestore export $BUCKET