name: Backup database

on:
  schedule:
    - cron:  '1/15 * * * *'

env:
  PROJECT_ID: ${{secrets.FIREBASE_DEV_PROJECT_ID}}
  BUCKET: gs://${{secrets.BUCKET_DEV}}

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@v1
        with:
          credentials_json: ${{ secrets.BACKUP_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud firestore export $BUCKET