name: Deployment to dev environment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      APP_DIR: ./app
      EXPORT_SCRIPT_DIR: ./export-script
      E2E_TESTS_DIR: ./e2e-tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Install app dependencies
        working-directory: ${{env.APP_DIR}}
        run: |
          npm install
      - name: Run frontend tests
        working-directory: ${{env.APP_DIR}}
        run: npm run test-ci
      - name: Run firestore tests
        working-directory: ${{env.APP_DIR}}
        run: npm run test-firestore
      - name: Install export script dependencies
        working-directory: ${{env.EXPORT_SCRIPT_DIR}}
        run: |
          npm install
      - name: Run export script tests
        working-directory: ${{env.EXPORT_SCRIPT_DIR}}
        run: npm test
      - name: Set environment variable with new version
        run: |
          PREVIOUS_VERSION=$(git fetch origin --tags -q && git describe --tags --match "dev-deployed-*" $(git rev-list --tags="dev-deployed-*" --max-count=1) | sed 's/[^0-9]*//g')
          echo "NEW_VERSION=$(($PREVIOUS_VERSION+1))" >> $GITHUB_ENV
      - name: Build production bundle
        env:
          REACT_APP_PROJECT_ID: ${{secrets.FIREBASE_DEV_PROJECT_ID}}
          REACT_APP_API_KEY: ${{secrets.FIREBASE_DEV_API_KEY}}
          REACT_APP_AUTH_DOMAIN: ${{secrets.FIREBASE_DEV_AUTH_DOMAIN}}
          REACT_APP_VERSION: ${{env.NEW_VERSION}}
        working-directory: ${{env.APP_DIR}}
        run: npm run build
      - name: Deploy to firebase
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
        working-directory: ${{env.APP_DIR}}
        run: |
          npx firebase use ${{secrets.FIREBASE_DEV_PROJECT_ID}}
          npx firebase deploy
      - name: Install e2e-tests dependencies
        working-directory: ${{env.E2E_TESTS_DIR}}
        run: |
          npm install
      - name: Run end to end tests
        env:
          ENDPOINT: ${{secrets.FIREBASE_DEV_ENDPOINT}}
          EMAIL: "test@test.com"
          PASSWORD: ${{secrets.FIREBASE_DEV_TEST_ACCOUNT_PASSWORD}}
          PROJECT_ID: ${{secrets.FIREBASE_DEV_PROJECT_ID}}
          API_KEY: ${{secrets.FIREBASE_DEV_API_KEY}}
          AUTH_DOMAIN: ${{secrets.FIREBASE_DEV_AUTH_DOMAIN}}
        working-directory: ${{env.E2E_TESTS_DIR}}
        run: node --experimental-vm-modules node_modules/jest/bin/jest.js
      - name: Create dev-deployed-* tag
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          TAG="dev-deployed-${{env.NEW_VERSION}}"
          git fetch --unshallow origin
          git tag $TAG $COMMIT_SHA
          git push origin $TAG
