name: BMMRO Frontend Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_DIR: ./app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install dependencies
        working-directory: ${{env.APP_DIR}}
        run: npm install
      - name: Run tests
        working-directory: ${{env.APP_DIR}}
        run: npm test
      - name: Build production bundle
        env:
          REACT_APP_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID_DEV}}
        working-directory: ${{env.APP_DIR}}
        run: npm run build
      - name: Deploy to firebase
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
        working-directory: ${{env.APP_DIR}}
        run: |
          sudo npm install -g firebase-tools
          firebase use ${{secrets.FIREBASE_PROJECT_ID_DEV}}
          firebase deploy
