name: Deployment to prod environment

on:
  push:
    tags:
      - "prod-pending-*"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      APP_DIR: ./app
      EXPORT_SCRIPT_DIR: ./export-script
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install app dependencies
        working-directory: ${{env.APP_DIR}}
        run: |
          npm install
      - name: Run frontend tests
        working-directory: ${{env.APP_DIR}}
        run: npm run test-ci
      - name: Run firestore tests
        working-directory: ${{env.APP_DIR}}
        run: npm run test-firestore
      - name: Install export script dependencies
        working-directory: ${{env.EXPORT_SCRIPT_DIR}}
        run: |
          npm install
      - name: Run export script tests
        working-directory: ${{env.EXPORT_SCRIPT_DIR}}
        run: npm test
      - name: Set environment variable with new version
        run: |
          PENDING_TAG=$(git fetch --tags -q && git tag -l | grep "prod-pending-*" | sort -V | tail -1)
          echo "PENDING_TAG=$PENDING_TAG" >> $GITHUB_ENV
          PENDING_TAG_VERSION=$(echo $PENDING_TAG | sed 's/[^0-9]*//g')
          echo "NEW_VERSION=$PENDING_TAG_VERSION" >> $GITHUB_ENV
      - name: Build production bundle
        env:
          REACT_APP_PROJECT_ID: ${{secrets.FIREBASE_PROD_PROJECT_ID}}
          REACT_APP_API_KEY: ${{secrets.FIREBASE_PROD_API_KEY}}
          REACT_APP_AUTH_DOMAIN: ${{secrets.FIREBASE_PROD_AUTH_DOMAIN}}
          REACT_APP_VERSION: ${{env.NEW_VERSION}}
          REACT_APP_ENCOUNTERS_BY_MONTH_DROPDOWN_FEATURE_TOGGLE: ${{secrets.ENCOUNTERS_BY_MONTH_DROPDOWN_FEATURE_TOGGLE_PROD}}
        working-directory: ${{env.APP_DIR}}
        run: npm run build
      - name: Deploy to firebase
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
        working-directory: ${{env.APP_DIR}}
        run: |
          npx firebase use ${{secrets.FIREBASE_PROD_PROJECT_ID}}
          npx firebase deploy
      - name: Update prod-pending-* tag to prod-deployed-*
        run: |
          TAG="prod-deployed-${{env.NEW_VERSION}}"
          git tag $TAG ${{env.PENDING_TAG}} -f
          git push origin $TAG -f
          git push origin --delete ${{env.PENDING_TAG}}
