name: Deployment to UAT environment

on:
  push:
    tags:
      - "uat-pending-*"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      APP_DIR: ./app
      SCRIPTS_DIR: ./export-script
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install app dependencies
        working-directory: ${{env.APP_DIR}}
        run: |
          npm install
          sudo npm install -g firebase-tools
      - name: Run frontend tests
        working-directory: ${{env.APP_DIR}}
        run: npm test
      - name: Run firestore tests
        working-directory: ${{env.APP_DIR}}
        run: npm run test-firestore
      - name: Install script dependencies
        working-directory: ${{env.SCRIPTS_DIR}}
        run: |
          npm install
          sudo npm install -g firebase-tools
      - name: Run scripts tests
        working-directory: ${{env.SCRIPTS_DIR}}
        run: npm test
      - name: Build production bundle
        env:
          REACT_APP_PROJECT_ID: ${{secrets.FIREBASE_UAT_PROJECT_ID}}
          REACT_APP_API_KEY: ${{secrets.FIREBASE_UAT_API_KEY}}
          REACT_APP_AUTH_DOMAIN: ${{secrets.FIREBASE_UAT_AUTH_DOMAIN}}
        working-directory: ${{env.APP_DIR}}
        run: npm run build
      - name: Deploy to firebase
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
        working-directory: ${{env.APP_DIR}}
        run: |
          firebase use ${{secrets.FIREBASE_UAT_PROJECT_ID}}
          firebase deploy
      - name: Update uat-pending-* tag to uat-deployed-*
        run: |
          git fetch origin --tags -q
          PENDING_TAG=$(git describe --tags --match "uat-pending-*" $(git rev-list --tags="uat-pending-*" --max-count=1))
          echo $PENDING_TAG
          VERSION=$(echo $PENDING_TAG | sed 's/[^0-9]*//g')
          TAG="uat-deployed-$VERSION"
          git tag $TAG $PENDING_TAG
          git push origin $TAG
          git push origin --delete $PENDING_TAG
