name: Deployment to UAT environment

on:
  push:
    tags:
      - "uat-pending-*"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      APP_DIR: ./app
      EXPORT_SCRIPT_DIR: ./export-script
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Install app dependencies
        working-directory: ${{env.APP_DIR}}
        run: |
          npm install
          sudo npm install -g firebase-tools
      - name: Run frontend tests
        working-directory: ${{env.APP_DIR}}
        run: npm test
      - name: Run firestore tests
        working-directory: ${{env.APP_DIR}}
        run: npm run test-firestore
      - name: Install export script dependencies
        working-directory: ${{env.EXPORT_SCRIPT_DIR}}
        run: |
          npm install
          sudo npm install -g firebase-tools
      - name: Run export script tests
        working-directory: ${{env.EXPORT_SCRIPT_DIR}}
        run: npm test
      - name: Set environment variable with new version
        run: |
          PENDING_TAG=$(git fetch origin --tags -q && git describe --tags --match "uat-pending-*" $(git rev-list --tags="uat-pending-*" --max-count=1))
          echo "::set-env name=PENDING_TAG::$PENDING_TAG"
          PENDING_TAG_VERSION=$(echo $PENDING_TAG | sed 's/[^0-9]*//g')
          echo "::set-env name=NEW_VERSION::$PENDING_TAG_VERSION"
      - name: Build production bundle
        env:
          REACT_APP_PROJECT_ID: ${{secrets.FIREBASE_UAT_PROJECT_ID}}
          REACT_APP_API_KEY: ${{secrets.FIREBASE_UAT_API_KEY}}
          REACT_APP_AUTH_DOMAIN: ${{secrets.FIREBASE_UAT_AUTH_DOMAIN}}
          REACT_APP_VERSION: ${{env.NEW_VERSION}}
        working-directory: ${{env.APP_DIR}}
        run: npm run build
      - name: Deploy to firebase
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
        working-directory: ${{env.APP_DIR}}
        run: |
          firebase use ${{secrets.FIREBASE_UAT_PROJECT_ID}}
          firebase deploy
      - name: Update uat-pending-* tag to uat-deployed-*
        run: |
          TAG="uat-deployed-${{env.NEW_VERSION}}"
          git tag $TAG ${{env.PENDING_TAG}} -f
          git push origin $TAG -f
          git push origin --delete ${{env.PENDING_TAG}}
